### PR TITLE
Introduction to UNICEF's OOI

### PR DESCRIPTION
**Pull request by ngcheryl**
Introduction to UNICEF's OOI work

### CODE REVIEW

**Comment by lacabra** [comment]
Hi @ngcheryl, thanks for your first contribution 🙌   💪

First of all, whenever something like this is ready for review, you have to request a review (from me) through the top right column, otherwise I don't know that this is ready for review, and would sit for days like it has so far 😉

**Comment by lacabra** [comment]
Because you are editing this as a markdown file, you have to label it as such, otherwise GitHub thinks it is a plain text file. I have gone ahead and made that change for you in commit 27f5ca0 by appending `.md` to the filename (which I have also shortened for convenience)

**Comment by lacabra** [comment]
It may take a little bit of time to get used to Markdown, for example when using headers `#` or `##` the bold is already added by default, so if you try to add it in addition to the header, it breaks the markdown. I have corrected these formatting glitches in f3a3186

**Review by lacabra — APPROVED** [review]
This looks good @ngcheryl 🙏

I have corrected a couple of very minor typos in 78229ea46e10aae357a2b145662dbe1389d739f3, and this is now ready for you to merge

**Comment by ngcheryl** [comment]
> Hi @ngcheryl, thanks for your first contribution 🙌 💪
> 
> First of all, whenever something like this is ready for review, you have to request a review (from me) through the top right column, otherwise I don't know that this is ready for review, and would sit for days like it has so far 😉

Ah got it! Makes sense. 👍 Thanks Victor for the tip.

**Pull request merged**
